// <auto-generated />
namespace stock_div.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class stocks2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stocks2));
        
        string IMigrationMetadata.Id
        {
            get { return "202002040343548_stocks2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
